services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    pull_policy: always
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${DOCKER_SERVER_PORT:-127.0.0.1:3000}:3000
    networks:
      - backend-net
    logging:
        driver: "json-file"
        options:
            max-size: "5m"
            max-file: "5"
  db:
    restart: 'no'
    image: mongo:6
    volumes:
      - './db-data:/data/db'
    ports:
      - '${DOCKER_MONGO_PORT:-127.0.0.1:27120}:27017'
    networks:
      - backend-net
    logging:
      options:
        max-size: "1m"
        max-file: "5"

networks:
  backend-net:

volumes:
  db-pgadmin:
