version: '3.4'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always
    restart: unless-stopped
    ports:
      - ${DOCKER_SERVER_PORT:-127.0.0.1:3000}:3000
    networks:
      - backend-net
    logging:
        driver: "json-file"
        options:
            max-size: "5m"

networks:
  backend-net:

volumes:
  db-pgadmin:
